### ISSUE TITLE
inqury: Build failure due to bloated script file

### ISSUE THREAD

**Issue by nemu1113** [kwchang0831/svelte-QWER#37]
What measures can be considered to reduce the chunk size?
When trying to build/deploy the materials, the following warnings and errors will occur and the build will fail.

The hosting service used is Cloudflare pages.

```pwsh
(!) Some chunks are larger than 500 KiB after minification. Consider:
 - Using dynamic import() to code-split the application
 - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
 - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
```

```pwsh
Error: Failed to publish your Function. Got error: Your Functions script is over the 1 MiB size limit (workers.api.error.script_too_large)
```

I'm guessing some modification is needed to the worker script.

■Build Command
npm run build
(npm-run-all -s build:QWER build:i18n build:sveltekit)

■System info (Cloudflare pages build environment)
node v16.17.1
NPM 8.15.0

**Comment by kwchang0831** [comment]
I never had luck with CF Pages. Please consider trying Vercel or Netlify.

## Possible root of cause
When number of posts is large, with current design, the post store/state management will get quite large, as well as the search function since it reads in all the contents.

To solve this, the design has to be rework, such as redesign posts store/state management, move in-site search to off-site dedicated site-search engine, eg. Agolia, and others...

Otherwise, I need to look into how to set up in vite to manually cut larger chunks into small pieces.

**Comment by nemu1113** [comment]
@kwchang0831 
I see. . This is a very thorny issue for me. 
Since it is not a new site, there was no plan to change the hosting destination, but I will consider it again.

**Comment by kwchang0831** [comment]
Migrate to new site is quite easy than solving this issue. You will have a peace of mind if you decided to do so. I personally suggest vercel. Transferring the domain should be seamlessly easy.

1. Get Vercel Account.
1. Deploy to Vercel, you will get a ****.vercel.app url, making sure everything is working.
1. Change the DNS record in CF to point to Vercel IP and then add the domain in vercel project setting.

**Comment by nemu1113** [comment]
@kwchang0831 
Thank you. 
By restricting the proposed proposal and the articles to be published, I found that it was possible to physically limit the file size and deploy it, so we will close this matter.

**Comment by kwchang0831** [comment]
Thanks ❤️
